{
 "title": "Hospital 2 - Local Training (Auto)",
 "tags": [
  "cardio",
  "hospital_2"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Test Accuracy",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "client_test_accuracy{job=\"client_2\"}"
    }
   ]
  },
  {
   "title": "Train Accuracy",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "client_train_accuracy{job=\"client_2\"}"
    }
   ]
  },
  {
   "title": "Val Accuracy",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "client_val_accuracy{job=\"client_2\"}"
    }
   ]
  },
  {
   "title": "XAI Score",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "client_xai_score{job=\"client_2\"}"
    }
   ]
  },
  {
   "title": "Last Round",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "client_last_round{job=\"client_2\"}"
    }
   ]
  },
  {
   "title": "Training Active",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "client_training_active{job=\"client_2\"}"
    }
   ]
  },
  {
   "title": "Train/Val Accuracy",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "client_train_accuracy{job=\"client_2\"}"
    },
    {
     "expr": "client_val_accuracy{job=\"client_2\"}"
    }
   ]
  },
  {
   "title": "Test Accuracy",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "client_test_accuracy{job=\"client_2\"}"
    }
   ]
  }
 ]
}