version: "3.8"

services:
  kafka:
    extends:
      file: infrastructure/kafka-compose.yml
      service: kafka

  zookeeper:
    extends:
      file: infrastructure/kafka-compose.yml
      service: zookeeper

  server:
    build: ./server
    depends_on:
      - kafka

  client:
    build: ./client
    depends_on:
      - kafka
